language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6.3
services:
  - postgresql
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp .env.test.sample .env.test
  - bundle exec hanami db prepare
